### PR TITLE
fixes #264 Fix invalid update command

### LINKED ISSUE #264: Constructed Update command is invalid
When I try to make an update operation on a Mongo 2.6 server using ReactiveMongo 0.11, server returns the error below:

```
{
  ok: BSONDouble(0.0),
  errmsg: BSONString(wrong type for 'updates' field contents, expected object, found 4),
  code: BSONInteger(9)
}
```

If I am not mistaken the key name for update elements in an Update command should be `updates` but it is `documents` on the master branch: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/commands/rwcommands.scala#L196

### PR DESCRIPTION
**Pull request by fehmicansaglam**

### CODE REVIEW

**Comment by cchantep** [comment]
Hi @fehmicansaglam , lgtm. Would you mind to rebase it against master? So it get validated with the CI.

**Comment by fehmicansaglam** [comment]
@cchantep sure.

**Comment by fehmicansaglam** [comment]
@cchantep Update command is only avaliable on 2.6.  But the Travis build uses Mongo 2.4. You may setup Mongo 2.6 like this: https://github.com/fehmicansaglam/tepkin/blob/master/.travis.yml

**Comment by cchantep** [comment]
Good catch @fehmicansaglam . Don't hesitate to create a PR to update MongoDB to 2.6 in CI config.

**Comment by cchantep** [comment]
Now it should be possible to properly rebase this one against master.

**Comment by fehmicansaglam** [comment]
@cchantep done.

**Comment by cchantep** [comment]
Thanks @fehmicansaglam . LGTM

**Comment by sgodbillon** [comment]
Thanks!

**Pull request merged**
