### PR TITLE
Fix summoning of BSONHandler[Seq[Int]]

### PR DESCRIPTION
**Pull request by jtjeferreira**
## Fixes

Fixes implicit resolution of `BSONHandler[Seq[Int]]` due to a problem in `reactivemongo.bson.DefaultBSONHandlers#findWriter`

### CODE REVIEW

**Comment by cchantep** [comment]
Thanks, rather check the new BSON API. This one will be remove after next major release.

**Comment by jtjeferreira** [comment]
The 2nd commit has the fix...

**Comment by jtjeferreira** [comment]
Hi @cchantep!

I am aware of the new API, and I think it is definitely an improvement over the current API. I am also aware of the compat layer that helps the migration...

The background of this fix is that I am working on using [magnolia](https://github.com/propensive/magnolia) to derive BSONWriters/BSONReaders/BSONHandlers, and this bug was preventing me to do it for BSONHandlers.
This bug is not a problem for the BSON API...

I will let you know when I have a more polished version, but meanwhile having this bug fixed would be awesome...

**Comment by cchantep** [comment]
Effort based on the old API are not recommended.

**Pull request closed without merging**
