### PR TITLE
Update to Scala 2.12.0

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by jbgi** [comment]
From what I understand, the major blocker for this update is [play-iteratees](https://github.com/playframework/play-iteratees) which have not been published against 2.12. On the other hand it seams that `play-iteratees` is being deprecated in favour of `akka-stream` and has not seen any update for months.

Can ReactiveMongo drop support for `play-iteratees` altogether?

**Comment by cchantep** [comment]
That's not the blocker

**Comment by alari** [comment]
@cchantep when are you going to make 0.12 release for scala 2.12? Is there any kind of snapshot to work with?

**Comment by cchantep** [comment]
When the required dependencies themselves will be available for 2.12.

**Pull request merged**
