### PR TITLE
Do not silently restart a new tailable cursor after maxDocs is reached.

### PR DESCRIPTION
**Pull request by jbgi**
Should resolve failing test of https://github.com/ReactiveMongo/ReactiveMongo-Streaming/pull/56.

### CODE REVIEW

**Comment by cchantep** [comment]
Any such change would need to update some cursor tests or to add some to demonstrate the validity of the change and the non-regression.

**Comment by jbgi** [comment]
I will try to come-up with some tests. But since this change impact only an api exclusively used by ReactiveMongo-Streaming (currently not tested in driver project), validating non regression would require running tests of that project against this PR. Is that possible?

**Comment by cchantep** [comment]
Tailable cursor is not only used by streaming. If there is an issue only in streaming, then no change there should fix it.

**Comment by jbgi** [comment]
Right, the method is used, it was just intellij "find usage" failing me.

**Comment by jbgi** [comment]
Added a test that ([fails](https://travis-ci.org/ReactiveMongo/ReactiveMongo/jobs/273031554#L2458)) without this fix.

**Pull request closed without merging**
