### PR TITLE
Fix getMore/session

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by ornicar** [comment]
ha, I was just about to submit a PR that fixes the `.map {` exhaustivity and the `.equals`!

ReactiveMongo won't build on scala 2.13.4 without that.

I have no idea what the new session code is about however.

**Comment by cchantep** [comment]
> @ornicar ha, I was just about to submit a PR that fixes the `.map {` exhaustivity and the `.equals`!
> 
> ReactiveMongo won't build on scala 2.13.4 without that.
> 
> I have no idea what the new session code is about however.

Building from sources?

**Comment by ornicar** [comment]
Yes I'm trying to fork reactivemongo to add monitoring and better understand what it's doing in prod conditions.

At the moment I'm mostly making NodeSetInfo available from the outside.

**Comment by cchantep** [comment]
> Yes I'm trying to fork reactivemongo to add monitoring and better understand what it's doing in prod conditions.
> 
> At the moment I'm mostly making NodeSetInfo available from the outside.

I think that's already possible, as done it in [ReactiveMongo-Monitoring](https://github.com/ReactiveMongo/ReactiveMongo-Monitoring/blob/master/kamon/src/main/scala/ConnectionListener.scala).

**Comment by ornicar** [comment]
This looks extremely useful, thanks.

**Pull request merged**
