### PR TITLE
Remove deprecated macro API usage

### PR DESCRIPTION
**Pull request by ddworak**
I needed to customize the handler macro for a personal project, so I thought it might be nice to remove deprecated API usage since I'm already there (even though I'm not much of a macro magician).

### CODE REVIEW

**Comment by cchantep** [comment]
Thanks for your contribution. The changes seem to break a lot of things.
You can run the tests locally, and/or have a look at the Travis log.
Best regards.

**Comment by ddworak** [comment]
I did run the test suites, it was just my eager renaming breaking binary compatibility. I added directories for version-specific source code in the macros subproject - the deprecated API was the only one in Scala 2.10. This seems to work quite fine on most platforms, the failures are quite cryptic to me e.g. ArrayIndexOutOfBoundsException while checking binary compatibility on Scala 2.10/oraclejdk8. Anything specific I should look into or are these unrelated?

**Comment by cchantep** [comment]
Please squash the commits

**Comment by ddworak** [comment]
Done.

**Comment by cchantep** [comment]
lgtm, thanks

**Comment by cchantep** [comment]
needs to be rebased

**Comment by ddworak** [comment]
done

**Comment by cchantep** [comment]
Thanks @ddworak , after the review, I suggest you update your PR according the following [Gist](https://gist.github.com/cchantep/59031490487f90c9a21c). Best regads.

**Comment by ddworak** [comment]
Thanks for great suggestions @cchantep! Everything should be fine now (although it seems the build was cancelled). Regards.

**Pull request merged**
