### PR TITLE
Fix `IllegalReferenceCountException` in `ResponseDecoder`

### PR DESCRIPTION
**Pull request by avdv**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/CONTRIBUTING.md#reactivemongo-developer--contributor-guidelines)?
* [x] Have you added tests for any changed functionality?

## Purpose

This fixes `io.netty.util.IllegalReferenceCountException`s to be thrown constantly in the `ResponseDecoder`. I noticed these exceptions when debugging [another problem](https://stackoverflow.com/questions/54706942/mongoerror-no-primary-node-is-available-decoderexception) we're seeing regarding "No primary node available" errors.

## Background Context

```
reactivemongo.io.netty.handler.codec.DecoderException: reactivemongo.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
 	at reactivemongo.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
 Caused by: reactivemongo.io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
 	at reactivemongo.io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:124)
 	at reactivemongo.io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:107)
 	at reactivemongo.io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:88)
 	at reactivemongo.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
 	at reactivemongo.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
 	at reactivemongo.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```
since the decoder will [release the ByteBuf itself](https://netty.io/4.1/api/io/netty/handler/codec/MessageToMessageDecoder.html)

> Be aware that you need to call ReferenceCounted.retain() on messages that are
> just passed through if they are of type ReferenceCounted. This is needed as
> the MessageToMessageDecoder will call ReferenceCounted.release() on decoded
>  messages.

I do not know (yet) whether this fixes my initial problem, but keeping it running under `-Dio.netty.leakDetectionLevel=paranoid` neither showed any leaks nor any `IllegalReferenceCountException` anymore.

### CODE REVIEW

**Comment by cchantep** [comment]
How to reproduce the initial issue? Because the tests were already "paranoid" for me and not encountering that.

**Comment by avdv** [comment]
You just need to set the logging level to `trace` and connect to mongod on localhost -- this guy will show up instantly.

Unfortunately, it seems not to fix the the issue with "No primary node available" errors we are seeing.

**Comment by avdv** [comment]
Oh, and maybe the log level should be changed -- an exception in the decoder is rather concerning, not something to let go by undetected...

**Comment by cchantep** [comment]
Please provide a reproducer, as I haven't seen such case locally.

**Comment by avdv** [comment]
I am on vacation right now. Will look into it next week.

**Comment by avdv** [comment]
#803 is simple reproducer for the exceptions. I am counting 27.687 errors for the integration test run with `CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.5.13 ITERATEES_VERSION=2.6.1 MONGO_PROFILE=default MONGO_VER=3` (here)[https://travis-ci.org/ReactiveMongo/ReactiveMongo/jobs/498030452].

**Pull request merged**
