### PR TITLE
Retry authentication until it succeeds

### PR DESCRIPTION
**Pull request by vvlevykin**
Use the failed authentication for retry too.

For #282.

### CODE REVIEW

**Comment by vvlevykin** [comment]
Now the authentication will be retried until it eventually succeeds.
But, as there is no retry interval, it retries immediately every time and CPU usage is 100% until it succeeds.

@sgodbillon, as I understand you are the right person to ask for advice how to solve it correctly.

**Comment by sgodbillon** [comment]
Hi @vvlevykin,

I think this retry should be left to the application side. As it is now, it's really hard to put an auth retry interval. But on the application side, this is quite easy to deal with: you may just `flatMap` on the future returned by `db.authenticate(user, passwd)` to create a future that "sleeps" for a little while before retrying. You can see the implementation of `Failover` to get a hint on how to that.

However, maybe we can provide a new method for this in the `DB` trait (or a new flag in the current `db.authenticate(user, passwd)` that does this automatically.)

**Comment by vvlevykin** [comment]
Is there a way to do authentication on the application side when the connection is lost and then restored?

I'm asking because there was a case when MongoDB nodes were replaced, but because of misconfiguration, the credentials for one of the databases were added a bit later and the app had to be restarted to continue working.
It's certainly possible to prevent it on another level, but I thought it would be not that bad to have resilience against that.

**Comment by sgodbillon** [comment]
Yes, you can call `db.authenticate(user, passwd)` again. A good way would be for you to provide a trigger (like a private rest API for example) in order to reauthenticate on demand by calling this method.

When you call `db.authenticate(user, passwd)`, if there is a successful authentication, it is stored in the connection pool metadata in order to automatically authenticate new connections. The problem is, when the authentication has failed, then it's not registered in the connection metadata. "Fixing" this should not be done, because it would mean that if did, all the new connections would automatically try to authenticate, which is likely to fail.

**Pull request closed without merging**
