### PR TITLE
Support for SocketTimeoutMS on URL connection

### PR DESCRIPTION
**Pull request by charleskubicek**
Implements semantics described in https://docs.mongodb.org/manual/reference/connection-string/#uri.socketTimeoutMS

### CODE REVIEW

**Comment by cchantep** [comment]
Hi, please squash the commits to a single one, so it can be reviewed. Best regards.

**Comment by charleskubicek** [comment]
Squashed commits into one.

**Comment by cchantep** [comment]
Thanks. It seems to break to timeout handling (see on Travis).

**Comment by cchantep** [comment]
Please rebase against master, to check whether there is any conflict.

**Comment by cchantep** [comment]
Please make sure to have run scalariform (`sbt scalariformFormat test:scalariformFormat`), so the coding style is not broken.

**Comment by cchantep** [comment]
Hi, the tests are needed. I prefer to wait they are fixed, rather than removing them. Thanks.

**Comment by charleskubicek** [comment]
Hi @cchantep, I have rebased. I have also temporarily removed the one test I added called "Connection should timeout when it is idle". This appeared to cause some other tests to fail for an unknown reason. The tests are now passing on Travis (except the JVM crashes). 

I wasn't happy with that test as it was too heavy-weight, can you think of a better way to test SocketTimeoutMS is correctly applied? Or, do we need to? All it does is delegate to Netty, but then we should unit test MongoHandler.

**Comment by cchantep** [comment]
@charleskubicek Why this test (which should be isolated) was slowing the other tests?

**Comment by cchantep** [comment]
Hi @charleskubicek, can it be tested using `netem` at first?

**Comment by charleskubicek** [comment]
Hi @cchantep, thanks for the tip, I'll take a look. We have been testing using a proxy service between the driver and Mongo to simulate slowdowns to test the idle trigger - so far it works well.

But I can't use `netem` in automated tests as it's not cross platform. We're going to look at other ways of unit testing it this week.

**Comment by cchantep** [comment]
As long as you can reproduce the test env using `netem`, that's ok, as it's already used for other integration tests. Let me know when you have something working in this way (and please rebase to keep up-to-date). Best regards.

**Comment by cchantep** [comment]
Hi, reintroduced an embedded [test proxy](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/test/scala/common.scala#L92). You may want to have a look at.

**Pull request closed without merging**
